import { Dancing_Script } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import PageTransition from "../components/PageTransition";
import StairTransition from "../components/StairTransition";
import Footer from "../components/Footer";

// Use correct font name
const dancingScript = Dancing_Script({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: '--font-dancing-script', // Use a meaningful name for the variable
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Use the correct font variable */}
      <body className={dancingScript.variable}>
        <Header />
        <StairTransition>{children}</StairTransition>
        <PageTransition>{children}</PageTransition>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
